name: Testing Cofiguration Variables

on:
    workflow_dispatch:

env:
    cloud: google-cloud

jobs:
    configuration-variable-job:
        runs-on: ubuntu-latest
        env:
            greeting: Hello
        steps:
          - name: "say hello"
            run: echo "$greeting $first_name is using $cloud The project name is ${{ vars.PROJECT_ID }}"
            env:
                first_name: subbarao
